### ISSUE TITLE
Missing inverse relations

### ISSUE THREAD

**Issue by ametke** [GA4GH-Pedigree-Standard/family_history_terminology#1]
Some missing inverse relations might be needed to build some of the axioms (e.g., role chaining). If these are added then I think we should adopt naming conventions similar to the ones used in the Family History Knowlege Base, e.g., isFatherOf - hasFather.

**Comment by buske** [comment]
Agree that since these are being modeled as ontology properties, rather than concepts, the naming should be explicit about direction.
