### ISSUE TITLE
Many of the Functional characteristics should be changed to InverseFunctional

### ISSUE THREAD

**Issue by cmungall** [GA4GH-Pedigree-Standard/family_history_terminology#29]
This can be seen by trying a probe class such as "Father of two":

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/50745/177630375-f666942a-7e49-49d4-9ad7-48b6414d2253.png">

**Comment by cmungall** [comment]
there are some cases where both relation and inverse are both declared functional e.g. isGestationalCarrierOf, this would make both functional and inverse-functional, i.e 1-to-1, meaning it is impossible to be gestational carrier of more than one child

**Comment by balhoff** [comment]
@buske @lindsmith I think my PR fixed Chris's issue; can it be closed?
