### ISSUE TITLE
Clarify dealing with triplets and higher order multiple births

### ISSUE THREAD

**Issue by buske** [GA4GH-Pedigree-Standard/family_history_terminology#3]
Feedback from Soichi Ogishima:

> Regarding Twin, isn't it something that comes under multiples, how do we deal with Triplets, quadruplets?

**Comment by ametke** [comment]
I guess we could rename to "isMultipleBirthSibling", "isMonozygoticMultipleBirthSibling" and "isPolyzygoticMultipleBirthSibling". Then we would just have relationships between all the siblings from the same birth. Thoughts @buske ?
