### ISSUE TITLE
isGreatGrandchildOf has incorrect altLabel

### ISSUE THREAD

**Issue by cmungall** [GA4GH-Pedigree-Standard/family_history_terminology#32]
altLabel should be used for alternative labels/synonyms/aliases

This would make this wrong:

isGreatGrandchildOf
skos:altLabel "hasGreatGrandparent"^^rdfs:Literal

the altlabel is actually for the inverse. Either name the inverse and make this string a property of that, or use a different annotation property such as antonymOf

**Comment by balhoff** [comment]
@cmungall I don't think you're right here. The inverse would be "isGreatGrandparentOf", but this is *has*.

Both make sense:

- `Annie isGreatGrandchildOf Erasmus`
- `Annie hasGreatGrandparent Erasmus`

**Comment by cmungall** [comment]
Doh, You're right! Somehow I missed the switch from child/parent in the
label
